// Copyright (C) 2012 Winterleaf Entertainment L,L,C.
// 
// THE SOFTW ARE IS PROVIDED ON AN “ AS IS” BASIS, WITHOUT W ARRANTY OF ANY KIND,
// INCLUDING WITHOUT LIMIT ATION THE W ARRANTIES OF MERCHANT ABILITY, FITNESS
// FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT . THE ENTIRE RISK AS TO THE
// QUALITY AND PERFORMANCE OF THE SOFTW ARE IS THE RESPONSIBILITY OF LICENSEE.
// SHOULD THE SOFTW ARE PROVE DEFECTIVE IN ANY RESPECT , LICENSEE AND NOT LICEN -
// SOR OR ITS SUPPLIERS OR RESELLERS ASSUMES THE ENTIRE COST OF AN Y SERVICE AND
// REPAIR. THIS DISCLAIMER OF W ARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS
// AGREEMENT. NO USE OF THE SOFTW ARE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
// 
// The use of the WinterLeaf Entertainment LLC DotNetT orque (“DNT ”) and DotNetT orque
// Customizer (“DNTC”)is governed by this license agreement (“ Agreement”).
// 
// R E S T R I C T I O N S
// 
// (a) Licensee may not: (i) create any derivative works of DNTC, including but not
// limited to translations, localizations, technology add-ons, or game making software
// other than Games; (ii) reverse engineer , or otherwise attempt to derive the algorithms
// for DNT or DNTC (iii) redistribute, encumber , sell, rent, lease, sublicense, or otherwise
// transfer rights to  DNTC; or (iv) remove or alter any tra demark, logo, copyright
// or other proprietary notices, legends, symbols or labels in DNT or DNTC; or (iiv) use
// the Software to develop or distribute any software that compete s with the Software
// without WinterLeaf Entertainment’s prior written consent; or (i iiv) use the Software for
// any illegal purpose.
// (b) Licensee may not distribute the DNTC in any manner.
// 
// LI C E N S E G R A N T .
// This license allows companies of any size, government entities or individuals to cre -
// ate, sell, rent, lease, or otherwise profit commercially from, games using executables
// created from the source code of DNT
// 
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// THE SOURCE CODE GENERATED BY DNTC CAN BE  DISTRIBUTED PUBLICLY PROVIDED THAT THE 
// DISTRIBUTOR PROVIDES  THE GENERATE SOURCE CODE FREE OF CHARGE.
// 
// THIS SOURCE CODE (DNT) CAN BE DISTRIBUTED PUBLICLY PROVIDED THAT THE DISTRIBUTOR 
// PROVIDES  THE SOURCE CODE (DNT) FREE OF CHARGE.
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// 
// Please visit http://www.winterleafentertainment.com for more information about the project and latest updates.
// 
// 
// 

#region

using System;
using System.ComponentModel;
using WinterLeaf.Classes;

#endregion

namespace WinterLeaf.tsObjects
    {
    /// <summary>
    /// 
    /// </summary>
    internal class tsObjectConvertercoForestBrushElement : TypeConverter
        {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <param name="sourceType"></param>
        /// <returns></returns>
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
            {
            return (typeof (string) == sourceType);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <param name="culture"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public override object ConvertFrom(ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value)
            {
            if (value is string)
                {
                return new coForestBrushElement(value as string);
                }

            return null;
            }
        }


    /// <summary>
    /// 
    /// </summary>
    [TypeConverter(typeof (tsObjectConvertercoForestBrushElement))]
    public class coForestBrushElement : coSimObject
        {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
        internal coForestBrushElement(string simobjectid) : base(simobjectid)
            {
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
        internal coForestBrushElement(uint simobjectid) : base(simobjectid)
            {
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
        internal coForestBrushElement(int simobjectid) : base(simobjectid)
            {
            }


        /// <summary>
        /// The max world space elevation this item will be placed. 
        /// </summary>
        public float elevationMax
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".elevationMax").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".elevationMax", value.AsString()); }
            }

        /// <summary>
        /// The min world space elevation this item will be placed. 
        /// </summary>
        public float elevationMin
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".elevationMin").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".elevationMin", value.AsString()); }
            }

        /// <summary>
        /// The type of ForestItem this element holds placement parameters for. 
        /// </summary>
        public coForestItemData forestItemData
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".forestItemData"); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".forestItemData", value.ToString()); }
            }

        /// <summary>
        /// The probability that this element will be created during an editor brush stroke      is the sum of all element probabilities in the brush divided by the probability      of this element. 
        /// </summary>
        public float probability
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".probability").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".probability", value.AsString()); }
            }

        /// <summary>
        /// The max rotation in degrees that items will be placed. 
        /// </summary>
        public float rotationRange
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".rotationRange").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".rotationRange", value.AsString()); }
            }

        /// <summary>
        /// An exponent used to bias between the minimum and maximum random sizes. 
        /// </summary>
        public float scaleExponent
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".scaleExponent").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".scaleExponent", value.AsString()); }
            }

        /// <summary>
        /// The maximum random size of each item. 
        /// </summary>
        public float scaleMax
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".scaleMax").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".scaleMax", value.AsString()); }
            }

        /// <summary>
        /// The minimum random size for each item. 
        /// </summary>
        public float scaleMin
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".scaleMin").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".scaleMin", value.AsString()); }
            }

        /// <summary>
        /// Max variation in the sink radius. 
        /// </summary>
        public float sinkMax
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".sinkMax").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".sinkMax", value.AsString()); }
            }

        /// <summary>
        /// Min variation in the sink radius. 
        /// </summary>
        public float sinkMin
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".sinkMin").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".sinkMin", value.AsString()); }
            }

        /// <summary>
        /// This is the radius used to calculate how much to sink the trunk at      its base and is used to sink the tree into the ground when its on a slope. 
        /// </summary>
        public float sinkRadius
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".sinkRadius").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".sinkRadius", value.AsString()); }
            }

        /// <summary>
        /// The max surface slope in degrees this item will be placed on. 
        /// </summary>
        public float slopeMax
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".slopeMax").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".slopeMax", value.AsString()); }
            }

        /// <summary>
        /// The min surface slope in degrees this item will be placed on. 
        /// </summary>
        public float slopeMin
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".slopeMin").AsFloat(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".slopeMin", value.AsString()); }
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <param name="simobjectid"></param>
        /// <returns></returns>
        public static bool operator ==(coForestBrushElement ts, string simobjectid)
            {
            if (object.ReferenceEquals(ts, null))
                return object.ReferenceEquals(simobjectid, null);
            return ts.Equals(simobjectid);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override int GetHashCode()
            {
            throw new NotImplementedException();
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public override bool Equals(object obj)
            {
            return (this._mSimObjectId == (string) myReflections.ChangeType(obj, typeof (string)));
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <param name="simobjectid"></param>
        /// <returns></returns>
        public static bool operator !=(coForestBrushElement ts, string simobjectid)
            {
            if (object.ReferenceEquals(ts, null))
                return !object.ReferenceEquals(simobjectid, null);
            return !ts.Equals(simobjectid);
            }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator string(coForestBrushElement ts)
            {
            if (object.ReferenceEquals(ts, null))
                return "0";
            return ts._mSimObjectId;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coForestBrushElement(string ts)
            {
            return new coForestBrushElement(ts);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator int(coForestBrushElement ts)
            {
            if (object.ReferenceEquals(ts, null))
                return 0;
            int i;
            return int.TryParse(ts._mSimObjectId, out i) ? i : 0;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coForestBrushElement(int ts)
            {
            return new coForestBrushElement(ts);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator uint(coForestBrushElement ts)
            {
            if (object.ReferenceEquals(ts, null))
                return 0;
            uint i;
            return uint.TryParse(ts._mSimObjectId, out i) ? i : 0;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coForestBrushElement(uint ts)
            {
            return new coForestBrushElement(ts);
            }
        }
    }