// Copyright (C) 2012 Winterleaf Entertainment L,L,C.
// 
// THE SOFTW ARE IS PROVIDED ON AN “ AS IS” BASIS, WITHOUT W ARRANTY OF ANY KIND,
// INCLUDING WITHOUT LIMIT ATION THE W ARRANTIES OF MERCHANT ABILITY, FITNESS
// FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT . THE ENTIRE RISK AS TO THE
// QUALITY AND PERFORMANCE OF THE SOFTW ARE IS THE RESPONSIBILITY OF LICENSEE.
// SHOULD THE SOFTW ARE PROVE DEFECTIVE IN ANY RESPECT , LICENSEE AND NOT LICEN -
// SOR OR ITS SUPPLIERS OR RESELLERS ASSUMES THE ENTIRE COST OF AN Y SERVICE AND
// REPAIR. THIS DISCLAIMER OF W ARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS
// AGREEMENT. NO USE OF THE SOFTW ARE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
// 
// The use of the WinterLeaf Entertainment LLC DotNetT orque (“DNT ”) and DotNetT orque
// Customizer (“DNTC”)is governed by this license agreement (“ Agreement”).
// 
// R E S T R I C T I O N S
// 
// (a) Licensee may not: (i) create any derivative works of DNTC, including but not
// limited to translations, localizations, technology add-ons, or game making software
// other than Games; (ii) reverse engineer , or otherwise attempt to derive the algorithms
// for DNT or DNTC (iii) redistribute, encumber , sell, rent, lease, sublicense, or otherwise
// transfer rights to  DNTC; or (iv) remove or alter any tra demark, logo, copyright
// or other proprietary notices, legends, symbols or labels in DNT or DNTC; or (iiv) use
// the Software to develop or distribute any software that compete s with the Software
// without WinterLeaf Entertainment’s prior written consent; or (i iiv) use the Software for
// any illegal purpose.
// (b) Licensee may not distribute the DNTC in any manner.
// 
// LI C E N S E G R A N T .
// This license allows companies of any size, government entities or individuals to cre -
// ate, sell, rent, lease, or otherwise profit commercially from, games using executables
// created from the source code of DNT
// 
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// THE SOURCE CODE GENERATED BY DNTC CAN BE  DISTRIBUTED PUBLICLY PROVIDED THAT THE 
// DISTRIBUTOR PROVIDES  THE GENERATE SOURCE CODE FREE OF CHARGE.
// 
// THIS SOURCE CODE (DNT) CAN BE DISTRIBUTED PUBLICLY PROVIDED THAT THE DISTRIBUTOR 
// PROVIDES  THE SOURCE CODE (DNT) FREE OF CHARGE.
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// 
// Please visit http://www.winterleafentertainment.com for more information about the project and latest updates.
// 
// 
// 

#region

using System;
using System.ComponentModel;
using WinterLeaf.Classes;

#endregion

namespace WinterLeaf.tsObjects
    {
    /// <summary>
    /// 
    /// </summary>
    internal class tsObjectConvertercoGuiWindowCtrl : TypeConverter
        {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <param name="sourceType"></param>
        /// <returns></returns>
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
            {
            return (typeof (string) == sourceType);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <param name="culture"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public override object ConvertFrom(ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value)
            {
            if (value is string)
                {
                return new coGuiWindowCtrl(value as string);
                }

            return null;
            }
        }


    /// <summary>
    /// 
    /// </summary>
    [TypeConverter(typeof (tsObjectConvertercoGuiWindowCtrl))]
    public class coGuiWindowCtrl : coGuiContainer
        {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
        internal coGuiWindowCtrl(string simobjectid) : base(simobjectid)
            {
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
        internal coGuiWindowCtrl(uint simobjectid) : base(simobjectid)
            {
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
        internal coGuiWindowCtrl(int simobjectid) : base(simobjectid)
            {
            }


        /// <summary>
        /// Whether the window has a close button. 
        /// </summary>
        public bool canClose
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".canClose").AsBool(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".canClose", value.AsString()); }
            }

        /// <summary>
        /// Whether the window can be collapsed by clicking its title bar. 
        /// </summary>
        public bool canCollapse
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".canCollapse").AsBool(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".canCollapse", value.AsString()); }
            }

        /// <summary>
        /// Whether the window has a maximize button. 
        /// </summary>
        public bool canMaximize
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".canMaximize").AsBool(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".canMaximize", value.AsString()); }
            }

        /// <summary>
        /// Whether the window has a minimize button. 
        /// </summary>
        public bool canMinimize
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".canMinimize").AsBool(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".canMinimize", value.AsString()); }
            }

        /// <summary>
        /// Whether the window can be moved by dragging its titlebar. 
        /// </summary>
        public bool canMove
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".canMove").AsBool(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".canMove", value.AsString()); }
            }

        /// <summary>
        /// Script code to execute when the window is closed. 
        /// </summary>
        public String closeCommand
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".closeCommand").AsString(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".closeCommand", value.AsString()); }
            }

        /// <summary>
        /// If true, the window will snap to the edges of other windows when moved close to them. 
        /// </summary>
        public bool edgeSnap
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".edgeSnap").AsBool(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".edgeSnap", value.AsString()); }
            }

        /// <summary>
        /// Whether the window can be resized vertically. 
        /// </summary>
        public bool resizeHeight
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".resizeHeight").AsBool(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".resizeHeight", value.AsString()); }
            }

        /// <summary>
        /// Whether the window can be resized horizontally. 
        /// </summary>
        public bool resizeWidth
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".resizeWidth").AsBool(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".resizeWidth", value.AsString()); }
            }

        /// <summary>
        /// Text label to display in titlebar. 
        /// </summary>
        public String text
            {
            get { return dnTorque.self.GetVar(_mSimObjectId + ".text").AsString(); }
            set { dnTorque.self.SetVar(_mSimObjectId + ".text", value.AsString()); }
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <param name="simobjectid"></param>
        /// <returns></returns>
        public static bool operator ==(coGuiWindowCtrl ts, string simobjectid)
            {
            if (object.ReferenceEquals(ts, null))
                return object.ReferenceEquals(simobjectid, null);
            return ts.Equals(simobjectid);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override int GetHashCode()
            {
            throw new NotImplementedException();
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public override bool Equals(object obj)
            {
            return (this._mSimObjectId == (string) myReflections.ChangeType(obj, typeof (string)));
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <param name="simobjectid"></param>
        /// <returns></returns>
        public static bool operator !=(coGuiWindowCtrl ts, string simobjectid)
            {
            if (object.ReferenceEquals(ts, null))
                return !object.ReferenceEquals(simobjectid, null);
            return !ts.Equals(simobjectid);
            }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator string(coGuiWindowCtrl ts)
            {
            if (object.ReferenceEquals(ts, null))
                return "0";
            return ts._mSimObjectId;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coGuiWindowCtrl(string ts)
            {
            return new coGuiWindowCtrl(ts);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator int(coGuiWindowCtrl ts)
            {
            if (object.ReferenceEquals(ts, null))
                return 0;
            int i;
            return int.TryParse(ts._mSimObjectId, out i) ? i : 0;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coGuiWindowCtrl(int ts)
            {
            return new coGuiWindowCtrl(ts);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator uint(coGuiWindowCtrl ts)
            {
            if (object.ReferenceEquals(ts, null))
                return 0;
            uint i;
            return uint.TryParse(ts._mSimObjectId, out i) ? i : 0;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coGuiWindowCtrl(uint ts)
            {
            return new coGuiWindowCtrl(ts);
            }

        /// <summary>
        ///  )
        /// 
        /// </summary>
        public void attachTo(string window)
            {
            TorqueScriptTemplate.m_ts.fnGuiWindowCtrl_attachTo(_mSimObjectId, window);
            }

        /// <summary>
        /// Bring the window to the front. )
        /// 
        /// </summary>
        public void selectWindow()
            {
            TorqueScriptTemplate.m_ts.fnGuiWindowCtrl_selectWindow(_mSimObjectId);
            }

        /// <summary>
        /// Set the window's collapsing state. )
        /// 
        /// </summary>
        public void setCollapseGroup(bool state)
            {
            TorqueScriptTemplate.m_ts.fnGuiWindowCtrl_setCollapseGroup(_mSimObjectId, state);
            }

        /// <summary>
        /// Toggle the window collapsing. )
        /// 
        /// </summary>
        public void toggleCollapseGroup()
            {
            TorqueScriptTemplate.m_ts.fnGuiWindowCtrl_toggleCollapseGroup(_mSimObjectId);
            }
        }
    }