
// Copyright (C) 2012 Winterleaf Entertainment L,L,C.
// 
// THE SOFTW ARE IS PROVIDED ON AN “ AS IS” BASIS, WITHOUT W ARRANTY OF ANY KIND,
// INCLUDING WITHOUT LIMIT ATION THE W ARRANTIES OF MERCHANT ABILITY, FITNESS
// FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT . THE ENTIRE RISK AS TO THE
// QUALITY AND PERFORMANCE OF THE SOFTW ARE IS THE RESPONSIBILITY OF LICENSEE.
// SHOULD THE SOFTW ARE PROVE DEFECTIVE IN ANY RESPECT , LICENSEE AND NOT LICEN -
// SOR OR ITS SUPPLIERS OR RESELLERS ASSUMES THE ENTIRE COST OF AN Y SERVICE AND
// REPAIR. THIS DISCLAIMER OF W ARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS
// AGREEMENT. NO USE OF THE SOFTW ARE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
// 
// The use of the WinterLeaf Entertainment LLC DotNetT orque (“DNT ”) and DotNetT orque
// Customizer (“DNTC”)is governed by this license agreement (“ Agreement”).
// 
// R E S T R I C T I O N S
// 
// (a) Licensee may not: (i) create any derivative works of DNTC, including but not
// limited to translations, localizations, technology add-ons, or game making software
// other than Games; (ii) reverse engineer , or otherwise attempt to derive the algorithms
// for DNT or DNTC (iii) redistribute, encumber , sell, rent, lease, sublicense, or otherwise
// transfer rights to  DNTC; or (iv) remove or alter any tra demark, logo, copyright
// or other proprietary notices, legends, symbols or labels in DNT or DNTC; or (iiv) use
// the Software to develop or distribute any software that compete s with the Software
// without WinterLeaf Entertainment’s prior written consent; or (i iiv) use the Software for
// any illegal purpose.
// (b) Licensee may not distribute the DNTC in any manner.
// 
// LI C E N S E G R A N T .
// This license allows companies of any size, government entities or individuals to cre -
// ate, sell, rent, lease, or otherwise profit commercially from, games using executables
// created from the source code of DNT
// 
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// THE SOURCE CODE GENERATED BY DNTC CAN BE  DISTRIBUTED PUBLICLY PROVIDED THAT THE 
// DISTRIBUTOR PROVIDES  THE GENERATE SOURCE CODE FREE OF CHARGE.
// 
// THIS SOURCE CODE (DNT) CAN BE DISTRIBUTED PUBLICLY PROVIDED THAT THE DISTRIBUTOR 
// PROVIDES  THE SOURCE CODE (DNT) FREE OF CHARGE.
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// 
// Please visit http://www.winterleafentertainment.com for more information about the project and latest updates.

#region
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WinterLeaf.Classes;
using WinterLeaf.Containers;
using WinterLeaf.Enums;
using System.ComponentModel;
#endregion

namespace WinterLeaf.tsObjects
    {
    /// <summary>
    /// 
    /// </summary>
    internal class tsObjectConvertercoNetConnection : TypeConverter
        {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <param name="sourceType"></param>
        /// <returns></returns>
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
            {
            return (typeof(string) == sourceType);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <param name="culture"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public override object ConvertFrom(ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value)
            {
            if (value is string)
                {
                return new coNetConnection(value as string);
                }

            return null;
            }
        }

      
    /// <summary>
    /// 
    /// </summary>
    [TypeConverter(typeof(tsObjectConvertercoNetConnection))]
    public class coNetConnection: coSimGroup
{
        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
public coNetConnection(string simobjectid) : base(simobjectid){ }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
public coNetConnection(uint simobjectid): base(simobjectid){ }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="simobjectid"></param>
public coNetConnection(int simobjectid): base(simobjectid){ }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <param name="simobjectid"></param>
        /// <returns></returns>
        public static bool operator ==(coNetConnection ts, string simobjectid)
            {
            if (object.ReferenceEquals(ts, null))
                return object.ReferenceEquals(simobjectid, null);
            return ts.Equals(simobjectid);


            }
  /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override int GetHashCode()
            {
            throw new NotImplementedException();
            }
  /// <summary>
        /// 
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public override bool Equals(object obj)
            {
            
            return (this._mSimObjectId ==(string)myReflections.ChangeType( obj,typeof(string)));
            }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <param name="simobjectid"></param>
        /// <returns></returns>
        public static bool operator !=(coNetConnection ts, string simobjectid)
            {
            if (object.ReferenceEquals(ts, null))
                return !object.ReferenceEquals(simobjectid, null);
            return !ts.Equals(simobjectid);

            }


            /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator string( coNetConnection ts)
            {
            return ts._mSimObjectId;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coNetConnection(string ts)
            {
            return new coNetConnection(ts);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator int( coNetConnection ts)
            {
            int i;
            return int.TryParse(ts._mSimObjectId, out i) ? i : 0;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coNetConnection(int ts)
            {
            return new coNetConnection(ts);
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator uint( coNetConnection ts)
            {
            uint i;
            return uint.TryParse(ts._mSimObjectId, out i) ? i : 0;
            }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ts"></param>
        /// <returns></returns>
        public static implicit operator coNetConnection(uint ts)
            {
            return new coNetConnection(ts);
            }
/// <summary>
/// @brief Ensures that all configured packet rates and sizes meet minimum requirements.
/// 
///    This method is normally only called when a NetConnection class is first constructed.  It need 
///    only be manually called if the global variables that set the packet rate or size have changed.
/// 
///    @note If @$pref::Net::PacketRateToServer, @$pref::Net::PacketRateToClient or @$pref::Net::PacketSize 
///    have been changed since a NetConnection has been created, this method must be called on 
///    all connections for them to follow the new rates or size.)
/// 
/// </summary>
public  void checkMaxRate(){
TorqueScriptTemplate.m_ts.fnNetConnection_checkMaxRate(_mSimObjectId);
}
/// <summary>
/// @brief On the server, resets the connection to indicate that motion spline paths have not been transmitted.
/// 
///    Typically when a mission has ended on the server, all connected clients are informed of this change 
///    and their connections are reset back to a starting state.  This method resets a connection on the 
///    server to indicate that motion spline paths have not been transmitted.
/// 
///    @tsexample
///       // Inform the clients
///       for (%clientIndex = 0; %clientIndex  ClientGroup.getCount(); %clientIndex++)
///       {
///          // clear ghosts and paths from all clients
///          %cl = ClientGroup.getObject(%clientIndex);
///          %cl.endMission();
///          %cl.resetGhosting();
///          %cl.clearPaths();
///       }
///    @endtsexample
///    
///    @see transmitPaths()
///    @see Path)
/// 
/// </summary>
public  void clearPaths(){
TorqueScriptTemplate.m_ts.fnNetConnection_clearPaths(_mSimObjectId);
}
/// <summary>
/// @brief Connects to the remote address.
/// 
///    Attempts to connect with another NetConnection on the given address.  Typically once 
///    connected, a game's information is passed along from the server to the client, followed 
///    by the player entering the game world.  The actual procedure is dependent on 
///    the NetConnection subclass that is used.  i.e. GameConnection.
/// 
///    @param remoteAddress The address to connect to in the form of IP:address>:port 
///    although the i>IP:/i> portion is optional.  The i>address/i> portion may be in the form 
///    of w.x.y.z or as a host name, in which case a DNS lookup will be performed.  You may also 
///    substitue the word i>broadcast/i> for the address to broadcast the connect request over 
///    the local subnet.
/// 
///    @see NetConnection::connectLocal() to connect to a server running within the same process 
///    as the client.
///    )
/// 
/// </summary>
public  void connect(string remoteAddress){
TorqueScriptTemplate.m_ts.fnNetConnection_connect(_mSimObjectId, remoteAddress);
}
/// <summary>
/// @brief Connects with the server that is running within the same process as the client.
/// 
///    @returns An error text message upon failure, or an empty string when successful.
/// 
///    @see See @ref local_connections for a description of local connections and their use.  See 
///    NetConnection::connect() to connect to a server running in another process (on the same machine or not).)
/// 
/// </summary>
public  string connectLocal(){
return TorqueScriptTemplate.m_ts.fnNetConnection_connectLocal(_mSimObjectId);
}
/// <summary>
/// @brief Returns the far end network address for the connection.
/// 
///    The address will be in one of the following forms:
///    - b>IP:Broadcast:port>/b> for broadcast type addresses
///    - b>IP:address>:port>/b> for IP addresses
///    - b>local/b> when connected locally (server and client running in same process)
/// 
/// </summary>
public  string getAddress(){
return TorqueScriptTemplate.m_ts.fnNetConnection_getAddress(_mSimObjectId);
}
/// <summary>
/// @brief On server or client, convert a real id to the ghost id for this connection.
/// 
///    Torque's network ghosting system only exchanges ghost ID's between the server and client.  Use 
///    this method on the server or client to discover an object's ghost ID based on its real SimObject ID.
/// 
///    @param realID The real SimObject ID of the object.
///    @returns The ghost ID of the object for this connection, or -1 if it could not be resolved.
/// 
///    @see @ref ghosting_scoping for a description of the ghosting system.)
/// 
/// </summary>
public  int getGhostID(int realID){
return TorqueScriptTemplate.m_ts.fnNetConnection_getGhostID(_mSimObjectId, realID);
}
/// <summary>
/// @brief Provides the number of active ghosts on the connection.
///    @returns The number of active ghosts.
///    @see @ref ghosting_scoping for a description of the ghosting system.)
/// 
/// </summary>
public  int getGhostsActive(){
return TorqueScriptTemplate.m_ts.fnNetConnection_getGhostsActive(_mSimObjectId);
}
/// <summary>
/// @brief Returns the percentage of packets lost per tick.
/// 
///    @note This method is not yet hooked up.)
/// 
/// </summary>
public  int getPacketLoss(){
return TorqueScriptTemplate.m_ts.fnNetConnection_getPacketLoss(_mSimObjectId);
}
/// <summary>
/// @brief Returns the average round trip time (in ms) for the connection.
/// 
///    The round trip time is recalculated every time a notify packet is received.  Notify 
///    packets are used to information the connection that the far end successfully received 
///    the sent packet.)
/// 
/// </summary>
public  int getPing(){
return TorqueScriptTemplate.m_ts.fnNetConnection_getPing(_mSimObjectId);
}
/// <summary>
/// @brief On the client, convert a ghost ID from this connection to a real SimObject ID.
/// 
///    Torque's network ghosting system only exchanges ghost ID's between the server and client.  Use 
///    this method on the client to discover an object's local SimObject ID when you only have a 
///    ghost ID.
/// 
///    @param ghostID The ghost ID of the object as sent by the server.
///    @returns The SimObject ID of the object, or 0 if it could not be resolved.
/// 
///    @tsexample
///       %object = ServerConnection.resolveGhostID( %ghostId );
///    @endtsexample
/// 
///    @see @ref ghosting_scoping for a description of the ghosting system.)
/// 
/// </summary>
public  int resolveGhostID(int ghostID){
return TorqueScriptTemplate.m_ts.fnNetConnection_resolveGhostID(_mSimObjectId, ghostID);
}
/// <summary>
/// @brief On the server, convert a ghost ID from this connection to a real SimObject ID.
/// 
///    Torque's network ghosting system only exchanges ghost ID's between the server and client.  Use 
///    this method on the server to discover an object's local SimObject ID when you only have a 
///    ghost ID.
/// 
///    @param ghostID The ghost ID of the object as sent by the server.
///    @returns The SimObject ID of the object, or 0 if it could not be resolved.
/// 
///    @tsexample
///       %object = %client.resolveObjectFromGhostIndex( %ghostId );
///    @endtsexample
/// 
///    @see @ref ghosting_scoping for a description of the ghosting system.)
/// 
/// </summary>
public  int resolveObjectFromGhostIndex(int ghostID){
return TorqueScriptTemplate.m_ts.fnNetConnection_resolveObjectFromGhostIndex(_mSimObjectId, ghostID);
}
/// <summary>
/// @brief Simulate network issues on the connection for testing.
/// 
///    @param packetLoss The fraction of packets that will be lost.  Ranges from 0.0 (no loss) to 1.0 (complete loss)
///    @param delay Delays packets being transmitted by simulating a particular ping.  This is an absolute 
///    integer, measured in ms.)
/// 
/// </summary>
public  void setSimulatedNetParams(float packetLoss, int delay){
TorqueScriptTemplate.m_ts.fnNetConnection_setSimulatedNetParams(_mSimObjectId, packetLoss, delay);
}
/// <summary>
/// @brief Sent by the server during phase 2 of the mission download to update motion spline paths.
/// 
///    The server transmits all spline motion paths that are within the mission (Path) separate from 
///    other objects.  This is due to the potentially large number of nodes within each path, which may 
///    saturate a packet sent to the client.  By managing this step separately, Torque has finer control 
///    over how packets are organised vs. doing it during the ghosting stage.
/// 
///    Internally a PathManager is used to track all paths defined within a mission on the server, and each 
///    one is transmitted using a PathManagerEvent.  The client side collects these events and builds the 
///    given paths within its own PathManager.  This is typically done during the standard mission start 
///    phase 2 when following Torque's example mission startup sequence.
/// 
///    When a mission is ended, all paths need to be cleared from their respective path managers.
/// 
///    @tsexample
///    function serverCmdMissionStartPhase2Ack(%client, %seq, %playerDB)
///    {
///       // Make sure to ignore calls from a previous mission load
///       if (%seq != $missionSequence || !$MissionRunning)
///          return;
///       if (%client.currentPhase != 1.5)
///          return;
///       %client.currentPhase = 2;
///    
///       // Set the player datablock choice
///       %client.playerDB = %playerDB;
///    
///       // Update mission paths (SimPath), this needs to get there before the objects.
///       %client.transmitPaths();
///    
///       // Start ghosting objects to the client
///       %client.activateGhosting();
///    }
///    @endtsexample
///    
///    @see clearPaths()
///    @see Path)
/// 
/// </summary>
public  void transmitPaths(){
TorqueScriptTemplate.m_ts.fnNetConnection_transmitPaths(_mSimObjectId);
}
}}
