// Copyright (C) 2012 Winterleaf Entertainment L,L,C.
// 
// THE SOFTW ARE IS PROVIDED ON AN “ AS IS” BASIS, WITHOUT W ARRANTY OF ANY KIND,
// INCLUDING WITHOUT LIMIT ATION THE W ARRANTIES OF MERCHANT ABILITY, FITNESS
// FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT . THE ENTIRE RISK AS TO THE
// QUALITY AND PERFORMANCE OF THE SOFTW ARE IS THE RESPONSIBILITY OF LICENSEE.
// SHOULD THE SOFTW ARE PROVE DEFECTIVE IN ANY RESPECT , LICENSEE AND NOT LICEN -
// SOR OR ITS SUPPLIERS OR RESELLERS ASSUMES THE ENTIRE COST OF AN Y SERVICE AND
// REPAIR. THIS DISCLAIMER OF W ARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS
// AGREEMENT. NO USE OF THE SOFTW ARE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
// 
// The use of the WinterLeaf Entertainment LLC DotNetT orque (“DNT ”) and DotNetT orque
// Customizer (“DNTC”)is governed by this license agreement (“ Agreement”).
// 
// R E S T R I C T I O N S
// 
// (a) Licensee may not: (i) create any derivative works of DNTC, including but not
// limited to translations, localizations, technology add-ons, or game making software
// other than Games; (ii) reverse engineer , or otherwise attempt to derive the algorithms
// for DNT or DNTC (iii) redistribute, encumber , sell, rent, lease, sublicense, or otherwise
// transfer rights to  DNTC; or (iv) remove or alter any tra demark, logo, copyright
// or other proprietary notices, legends, symbols or labels in DNT or DNTC; or (iiv) use
// the Software to develop or distribute any software that compete s with the Software
// without WinterLeaf Entertainment’s prior written consent; or (i iiv) use the Software for
// any illegal purpose.
// (b) Licensee may not distribute the DNTC in any manner.
// 
// LI C E N S E G R A N T .
// This license allows companies of any size, government entities or individuals to cre -
// ate, sell, rent, lease, or otherwise profit commercially from, games using executables
// created from the source code of DNT
// 
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// THE SOURCE CODE GENERATED BY DNTC CAN BE  DISTRIBUTED PUBLICLY PROVIDED THAT THE 
// DISTRIBUTOR PROVIDES  THE GENERATE SOURCE CODE FREE OF CHARGE.
// 
// THIS SOURCE CODE (DNT) CAN BE DISTRIBUTED PUBLICLY PROVIDED THAT THE DISTRIBUTOR 
// PROVIDES  THE SOURCE CODE (DNT) FREE OF CHARGE.
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// 
// Please visit http://www.winterleafentertainment.com for more information about the project and latest updates.
// 
// 
// 

#region

using System.Linq;
using WinterLeaf.Classes;
using WinterLeaf.tsObjects;

#endregion

namespace DNT_FPS_Demo_Game_Dll.Scripts.Server
    {
    public partial class Main : TorqueScriptTemplate
        {
        [Torque_Decorations.TorqueCallBack("", "", "centerPrintAll", "(%message, %time, %lines)", 3, 20000, false)]
        public void CenterPrintAll(string message, string time, string lines)
            {
            if (lines == "" || lines.AsInt() > 3 || lines.AsInt() < 1)
                lines = "1";

            foreach (coGameConnection client in ClientGroup.Where(client => !((coGameConnection) client).isAIControlled()))
                console.commandToClient(client, "centerPrint", new[] {message, time, lines});
            }

        [Torque_Decorations.TorqueCallBack("", "", "bottomPrintAll", "(%message, %time, %lines)", 3, 20000, false)]
        public void BottomPrintAll(string message, string time, string lines)
            {
            if (lines == "" || lines.AsInt() > 3 || lines.AsInt() < 1)
                lines = "1";
            foreach (coGameConnection client in ClientGroup.Where(client => !((coGameConnection) client).isAIControlled()))
                console.commandToClient(client, "bottomPrint", new[] {message, time, lines});
            }

        [Torque_Decorations.TorqueCallBack("", "", "centerPrint", "(%client,%message, %time, %lines)", 4, 20000, false)]
        public void CenterPrint(coGameConnection client, string message, string time, string lines)
            {
            if (lines == "" || lines.AsInt() > 3 || lines.AsInt() < 1)
                lines = "1";

            console.commandToClient(client, "centerPrint", new[] {message, time, lines});
            }

        [Torque_Decorations.TorqueCallBack("", "", "bottomPrint", "(%client,%message, %time, %lines)", 4, 20000, false)]
        public void BottomPrint(coGameConnection client, string message, string time, string lines)
            {
            if (lines == "" || lines.AsInt() > 3 || lines.AsInt() < 1)
                lines = "1";

            console.commandToClient(client, "bottomPrint", new[] {message, time, lines});
            }

        [Torque_Decorations.TorqueCallBack("", "", "clearCenterPrint", "(%client)", 1, 20000, false)]
        public void ClearCenterPrint(coGameConnection client)
            {
            console.commandToClient(client, "ClearCenterPrint");
            }

        [Torque_Decorations.TorqueCallBack("", "", "clearBottomPrint", "(%client)", 1, 20000, false)]
        public void ClearBottomPrint(coGameConnection client)
            {
            console.commandToClient(client, "clearBottomPrint");
            }

        [Torque_Decorations.TorqueCallBack("", "", "clearCenterPrint", "()", 0, 20000, false)]
        public void ClearCenterPrintAll()
            {
            foreach (coGameConnection client in ClientGroup.Cast<coGameConnection>().Where(client => !client.isAIControlled()))
                console.commandToClient(client, "ClearCenterPrint");
            }

        [Torque_Decorations.TorqueCallBack("", "", "clearBottomPrint", "()", 0, 20000, false)]
        public void ClearBottomPrintAll()
            {
            foreach (coGameConnection client in ClientGroup.Cast<coGameConnection>().Where(client => !client.isAIControlled()))
                console.commandToClient(client, "clearBottomPrint");
            }
        }
    }